name: sos_alert_number
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  telephony: ^0.2.0
  permission_handler: ^11.0.1
  camera: ^0.10.5+9
  geolocator: ^14.0.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"